server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8761/eureka/
    tls:
      enabled: false
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://service-provider
          predicates:
            - Path=/service-provider/**
  application:
    name: api-gateway