spring:
  profiles:
    active: peer1
  application:
    name: service-discovery
  security:
    user:
      name: admin
      password: pwd
---
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@peer2:8762/eureka/
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 8761
---
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@peer1:8761/eureka/
spring:
  config:
    activate:
      on-profile: peer2
server:
  port: 8762